# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Django application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev,unit,integration]
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: Check quality with bandit
      run: |
        # stop the build if there are Python syntax errors or undefined names
        bandit -r . -x ./test,./venv
    - name: Test with pytest
      run: |
        python manage.py runserver > output.log 2>&1 < /dev/null &
        pytest --cov --cov-report xml  test/
        kill $(ps aux | grep 'runserver' | awk '{print $2}')
    - name: Build the Docker image
      run: |
        pwd
        ls -la
        docker build . --file Dockerfile --tag ttd-python:$(date +%s)
